<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByCategory($name)
    {
        $repository = $this->getEntityManager()->getRepository('AppBundle:Category');

        $category = null;

        $query = $repository->createQueryBuilder('c')
            ->where('c.name = :name')
            ->setParameter('name', $name)
            ->getQuery();

        try {
            $category = $query->setMaxResults(1)->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }

        $posts = array();

        if ($category) {
            $query = $this->createQueryBuilder('p')
                ->where('p.category = :category')
                ->setParameter('category', $category)
                ->getQuery();

            $posts = $query->getResult();
        }

        return $posts;
    }

}
