
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /recipe/all

home_page:
    path:      /recipe/{name}
    defaults:  { _controller: AppBundle:Default:index }
    defaults:   { name: 'all' }

new_post:
    path:      /new
    defaults:  { _controller: AppBundle:Default:save }

show_post:
    path:      /show/{id}
    defaults:  { _controller: AppBundle:Default:show }

home_category:
    path:      /category/
    defaults:  { _controller: AppBundle:Category:index }
new_category:
    path:      /category/new
    defaults:  { _controller: AppBundle:Category:save }
